---
kind: pipeline
name: default

steps: 
- name: test
  image: node:8
  commands:
  - npm install
  - npm test

- name: build
  image: node:8
  commands:
  - "npm run build"
  when:
    event:
    - push
    - tag

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: Dockerfile
    repo: registry.cn-hongkong.aliyuncs.com/unex/drone-demo
    registry: registry.cn-hongkong.aliyuncs.com 
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: deploy
  image: quay.io/honestbee/drone-kubernetes
  kubernetes_server: ${KUBERNETES_SERVER}
  kubernetes_cert: ${KUBERNETES_CERT}
  kubernetes_token: ${KUBERNETES_TOKEN}
  deployment: drone-demo
  repo: registry.cn-hongkong.aliyuncs.com/unex/drone-demo
  container:  drone-demo
  namespace: app
  tag:                 
      - latest
  when:
    event:
    - push
    - tag
