---
kind: pipeline
name: default

steps: 
- name: test
  image: node:8
  commands:
  - npm install
  - npm test

- name: build
  image: node:8
  commands:
  - "npm run build"
  when:
    event:
    - push
    - tag

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: Dockerfile
    repo: registry.cn-hongkong.aliyuncs.com/unex/drone-demo
    registry: registry.cn-hongkong.aliyuncs.com 
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

- name: deploy
  image: lachlanevenson/k8s-kubectl
  environment:
    KUBE_CONFIG:
      from_secret: kube_config
  commands:
    - echo $KUBE_CONFIG
    - mkdir /root/.kube
    - cat $KUBE_CONFIG > /root/.kube/config
    - kubectl apply -f deployment.yaml
