---
kind: pipeline
name: default

steps: 
- name: test
  image: node:8
  commands:
  - npm install
  - npm test

- name: build
  image: node:8
  commands:
  - "npm run build"
  when:
    event:
    - push
    - tag

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: reonzhao/drone-demo
    tags: latest
    username: reonzhao
    password: 19842895
  when:
    event:
    - push
    - tag