apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  generation: 2
  labels:
    app: drone-demo
    run: drone-demo
    service: drone-demo
  name: drone-demo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: drone-demo
      run: drone-demo
      service: drone-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drone-demo
        run: drone-demo
        service: drone-demo
    spec:
      containers:
        - image: 'registry.cn-hongkong.aliyuncs.com/unex/drone-demo:latest'
          imagePullPolicy: Always
          name: drone-demo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: rdc-image-pull-secret-registry.cn-hongkong.aliyuncs.com
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30